language: rust
cache: cargo

dist: bionic
sudo: required
addons:
  apt:
    packages:
      - libasound-dev
      - libopus-dev

before_script:
  - rustup component add clippy

script:
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
