[package]
name = "netsound-audio-backend-cpal"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"
license = "AGPL-3.0-only"

[dependencies]
netsound-core = { version = "0.1", path = "../netsound-core" }
cpal = "0.13"
futures = "0.3"
derivative = "2"
