[package]
name = "netsound"
version = "0.1.0"
authors = ["MOZGIII <mike-n@narod.ru>"]
edition = "2018"
license = "AGPL-3.0-only"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
netsound-core = { version = "0.1", path = "../" }
async-trait = "0.1"
audiopus = "0.2"
byteorder = "1.3"
cpal = "0.11"
dasp_frame = "0.11"
dasp_interpolate = { version = "0.11", features = ["linear"] }
dasp_sample = "0.11"
dasp_signal = "0.11"
erased-serde = "0.3"
failure = "0.1"
futures = { version = "0.3", features = ["unstable", "async-await", "bilock"] }
serde = { version = "1.0", features = ["derive"] }
slog = { version = "2.5", features = ["nested-values"] }
slog_derive = "0.2"
slog-env-cfg = "0.6"
slog-json = { version = "2.3", features = ["nested-values"] }
slog-scope = "4.3"
slog-scope-futures = "0.1"
tokio = { version = "0.2", features = ["full"] }
